org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

minecraft_version=26.1
loader_version=0.18.4
fabric_api_version=0.145.1+26.1
modmenu_version=18.0.0-alpha.8
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.0
maven_group=one.yuqas
archives_base_name=TrTierListTagger
